# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Resume CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build Angular App
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --prod --base-href "/resume/"
      
    - name: deploy to github pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        build_dir: "./dist/Resume/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
